### ISSUE TITLE
how to use controlnet?

### ISSUE THREAD

**Issue by eslinan** [kyle-github/libplctag#85]
hello, i have two backplanes communicate with controlnet, how can I set the path to create new tag? I tried "path=1,0,2,2,1,0", 1 is backplane, 0 is controlnet slot, 2 is controlnet, 2 is controlnet slot, 1 is backplane, 0 is cpu slot, but it seems wrong, which is the right way?

**Comment by kyle-github** [comment]
I do not have any ControlNet examples and have not tested this with ControlNet.   

I think this might not be correct.   If it is anything like DH+, then it would be:

    1 - backplane
    0 - chassis slot in which the ControlNet card sits (usually zero is used for the CPU)
    2 - port on the ControlNet card on which the ControlNet network is connected.
    ? - the ControlNet ID of the target machine.
    1 - backplane
    0 - the slot in which the CPU of the remote machine sits.

The "?" is there because in your explanation you mentioned the slot.   If that is not a typo, then that is probably wrong.  You want the node ID on ControlNet for the remote system.   There may be some limitations in the library for large numbers, so try to keep them small.

I want to make this work, so please let me know if the above change works for you!  

If it does not, I will try to help debug the problem.  However, I will be travelling for work the next week and will be away from my development systems.

Best,
Kyle

**Comment by eslinan** [comment]
oh, recently, there have been many things, and I have replaced them with opc for the time being. The next holiday may be studied carefully.

**Comment by kyle-github** [comment]
Can we close this until you have some time to debug again?

**Comment by kyle-github** [comment]
Please reopen if you get a chance to test again.  Thanks!
